apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-github-0vb4iiiqx97wg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-github-0vb4iiiqx97wg
    app.kubernetes.io/part-of: application-github-5a2y2int779ox
  name: component-github-0vb4iiiqx97wg
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: component-github-0vb4iiiqx97wg
status:
  loadBalancer: {}
